---
name: zls
description: Zig LSP implementation + Zig Language Server.
homepage: https://github.com/zigtools/zls
licenses:
  - MIT
languages:
  - Zig
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/zigtools/zls@d1d4e60d543812231e3afe977f32fc6846c83962
  build:
    - target: unix
      run: |
        zig build -Doptimize=ReleaseSafe

schemas:
  lsp: vscode:https://raw.githubusercontent.com/zigtools/zls-vscode/master/package.json

bin:
  zls: "bin/zls"

# zstd is unavailable on runners.
ci_skip:
  - darwin_x64
  - darwin_arm64
  - win_arm
  - win_arm64
  - win_x64
  - win_x86
